"use client";

import React, { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { useAuthOptional } from "../../../../../../components/auth/AuthProvider";
import { getEvent, type EventWithRecipes } from "../../../../../../lib/api";
import { listRecipes, type SavedRecipe } from "../../../../../../lib/api";
import { buildGroceryListForEvent } from "../../../../../../lib/grocery";
import { isDemoMode } from "../../../../../../lib/demo";
import Logo from "../../../../../../components/Logo";

export default function PrintGroceryPage() {
  const params = useParams();
  const eventId = params.id as string;
  const { session, loading: authLoading } = useAuthOptional();
  
  const [event, setEvent] = useState<EventWithRecipes | null>(null);
  const [allRecipes, setAllRecipes] = useState<SavedRecipe[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (authLoading) return;

    if (!session) {
      window.location.href = "/auth/sign-in";
      return;
    }

    loadData();
  }, [session, authLoading, eventId]);

  const loadData = async () => {
    if (!session) return;

    try {
      setLoading(true);
      const [eventData, recipesData] = await Promise.all([
        getEvent(eventId, session),
        listRecipes(session),
      ]);
      setEvent(eventData);
      setAllRecipes(recipesData);
    } catch (err) {
      console.error("Failed to load grocery data:", err);
    } finally {
      setLoading(false);
    }
  };

  if (loading || !event) {
    return (
      <div className="print-page">
        <p>Loading...</p>
      </div>
    );
  }

  const { recipes, itemsBySection } = buildGroceryListForEvent(event, allRecipes);
  const recipeNames = recipes.map((r) => r.title).join(", ");
  
  const formatDate = (dateString: string | null) => {
    if (!dateString) return "No date set";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      weekday: "short",
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    });
  };

  return (
    <div className="print-page">
      {/* Header */}
      <div className="print-header mb-6">
        <div className="flex justify-between items-start">
          <div>
            <Logo variant="mono" withWordmark={false} className="mb-4" />
          </div>
          <div className="text-right">
            <h1 className="text-2xl font-bold text-ink mb-1">GROCERY LIST</h1>
            <p className="text-base text-ink font-medium">
              {event.name} {event.headcount && `• ${event.headcount} guests`}
            </p>
            {event.event_date && (
              <p className="text-sm text-text-muted mt-1">
                {formatDate(event.event_date)}
              </p>
            )}
            <p className="text-xs text-text-muted mt-2">
              Covers: {recipeNames || "No recipes"}
            </p>
            <p className="text-xs text-text-muted mt-1">
              Generated by Catered By Me — Host the meal. We&apos;ve got the rest.
            </p>
          </div>
        </div>
        <div className="border-t border-gray-300 mt-4 pt-4"></div>
      </div>

      {/* Body - Two column layout */}
      <div className="print-columns">
        {itemsBySection.map((section) => (
          <div key={section.section} className="print-section-card mb-6">
            <h2 className="text-lg font-semibold text-accent-primary mb-3 uppercase tracking-wide">
              {section.label}
            </h2>
            <ul className="space-y-2">
              {section.items.map((item) => (
                <li key={item.id} className="text-sm">
                  <span className="inline-block w-4 h-4 border border-ink mr-2 align-middle"></span>
                  {item.quantity && (
                    <span className="font-medium">{item.quantity} </span>
                  )}
                  <span>{item.name}</span>
                  {item.recipeNames.length > 0 && (
                    <div className="text-xs text-text-muted ml-6 mt-0.5">
                      In: {item.recipeNames.join(", ")}
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="print-footer mt-8 pt-4 border-t border-gray-300">
        <div className="flex justify-between items-center">
          <p className="text-xs text-text-muted">
            Built by Catered By Me — You know what looks good. We know how to get you there.
          </p>
          <p className="text-xs text-text-muted">Page 1 of 1</p>
        </div>
      </div>
    </div>
  );
}
